version: '3'

services:
  dashboard:
    build: .
    container_name: dashboard
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge 